# SITE CONFIGURATION
baseurl: "/end19"
url: "https://cholahan.github.io"
title: Geocoding Early Novels # site's title
description: "Mapping the locations in 18th century novels' title pages" # used by search engines

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/img/logo.jpg # seo tag

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/logo.jpg
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: Mapping locations in the title pages of 18th century novels
  header_feature_image: assets/img/map_africa.jpg
  footer_text: >
    A project using <a href="https://earlynovels.github.io/" target="blank">END Data</a></a>

  # Icons
  rss:   # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github:
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin:
    wordpress:
    email: true

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# AUTHORS
authors:
  cassidy: # author-id
    name: Cassidy Holahan
    avatar: "assets/img/avatars/cassidy_avatar.jpg"
    url:
  ina:
    name: Ina Chen
    avatar: "assets/img/avatars/ina.jpg"
    url: "https://github.com/redadvance"
  thyo:
    name: Dorothy Pierre-Louis
    avatar: "assets/img/avatars/thyo_avatar.png"
    url:

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
